version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: db-mysql
    ports:
      - "3309:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_USER=golang-crud
      - MYSQL_PASSWORD=golang-crud
      - MYSQL_ROOT_PASSWORD=golang-crud
      - MYSQL_DATABASE=golang-crud
    networks:
      - app-network

  redis:
    image: redis:6.2
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  golang:
    build: .
    container_name: golang-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
