
CREATE TABLE IF NOT EXISTS `cart`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_serial VARCHAR(255) NOT NULL,
    product_serial VARCHAR(255) NOT NULL,
    quantity INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
    );