
CREATE TABLE IF NOT EXISTS `checkout`
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    cart_id BIGINT NOT NULL,
    user_serial VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
    );